port: 8000
host: 127.0.0.1
api_prefix: "/api/v1"

resourceTimeout: 5
analyticsTimeout: 15

resource_host: 127.0.0.1
resource_port: 8001
resource_api_prefix: "/resource/"

analytics_host: 127.0.0.1
analytics_port: 8002
analytics_api_prefix: "/graph/"

connector_host: 127.0.0.1
connector_port: 8003
connector_api_prefix: "/connector/"

db_host: localhost
db_port: 5432
db_name: testdb
db_user: postgres
db_passwd: password

local_http_server_port: 8003
local_http_server_host: localhost
jiraUrl: https://issues.apache.org/jira
issueInOneRequest: 100
threadCount: 10
maxTimeSleep: 8000
minTimeSleep: 50
