port: 8000
host: 127.0.0.1
api_prefix: "/api/v1"

resourceTimeout: 5
analyticsTimeout: 1

resource_host: 127.0.0.1
resource_port: 8001
resource_api_prefix: "/resource/"

analytics_host: 127.0.0.1
analytics_port: 8002
analytics_api_prefix: "/graph/"

connector_host: 127.0.0.1
connector_port: 8081
connector_api_prefix: "/connector/"