DBSettings:
  username: postgres
  password: admin
  hostname: localhost
  port: 49153
  name: testdb
ProgramSettings:
  local_http_server_port: 8081
  local_http_server_host: "localhost"
  jiraUrl: https://issues.apache.org/jira
  issueInOneRequest: 100
  threadCount: 10
  maxTimeSleep: 8000
  minTimeSleep: 50
