DBSettings:
  username: postgres
  password: postgres
  hostname: localhost
  port: 5432
  name: postgres
ProgramSettings:
  local_http_server_port: 8081
  jiraUrl: https://issues.apache.org/jira
  issueInOneRequest: 100
  threadCount: 10
  maxTimeSleep: 8000
  minTimeSleep: 50
